name: News Update

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update news
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency: news-update
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@ed8efb33836e8b2096c7fd3ba1c8afe303ebbff1 # 1.6

      - name: Run news:update on production
        run: flyctl ssh console -a lingonews -C "bin/rails news:update"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
